import sqlite3
c = sqlite3.connect(r'E:\ICON\backend\icon_app.db')
cur = c.cursor()
print(f'Projects: {cur.execute("SELECT COUNT(*) FROM projects").fetchone()[0]}')
print(f'Project Items: {cur.execute("SELECT COUNT(*) FROM project_items").fetchone()[0]}')
print(f'Persons: {cur.execute("SELECT COUNT(*) FROM person").fetchone()[0]}')
print(f'Structures: {cur.execute("SELECT COUNT(*) FROM structures").fetchone()[0]}')
print(f'Crops: {cur.execute("SELECT COUNT(*) FROM crops").fetchone()[0]}')
print(f'Components: {cur.execute("SELECT COUNT(*) FROM components").fetchone()[0]}')
print(f'Orphan items: {cur.execute("SELECT COUNT(*) FROM project_items pi LEFT JOIN projects p ON pi.project_id=p.id WHERE p.id IS NULL").fetchone()[0]}')
print(f'Items per project (first 5): {cur.execute("SELECT project_id,COUNT(*) FROM project_items GROUP BY project_id ORDER BY project_id LIMIT 5").fetchall()}')
print(f'Line types: {[r[0] for r in cur.execute("SELECT DISTINCT line_type FROM project_items").fetchall()]}')
print(f'Project 1 code: {cur.execute("SELECT id, project_code, project_name FROM projects WHERE id=1").fetchone()}')
c.close()
